version: '2.2'

services:
  config-server:
    image: config-server
    restart: always
    ports:
      - 8888:8888

  service-discovery:
    image: service-discovery
    restart: always
    ports:
      - 8761:8761
    depends_on:
      config-server:
        condition: service_healthy

  gateway:
    image: gateway
    restart: always
    ports:
      - 8080:8080
    depends_on:
      service-discovery:
        condition: service_healthy

  hello-service:
    image: hello-service
    restart: always
    depends_on:
      - gateway
